### ISSUE TITLE
Fallos traducción español

### ISSUE THREAD

**Issue by migui88** [ingbrzy/MA-XML-9.0-SPANISH#1]
Hola,
He encontrado estos fallos de traducción en un redmi 4 con la última versión de MIUI9. 
Saludos!
![screenshot_2017-09-28-21-16-05](https://user-images.githubusercontent.com/10882140/31007823-18cc1976-a502-11e7-823c-3b809e80d48f.png)
![screenshot_2017-09-28-21-16-15](https://user-images.githubusercontent.com/10882140/31007824-18ccc998-a502-11e7-8010-0d24f3803869.png)
![screenshot_2017-09-28-21-23-35](https://user-images.githubusercontent.com/10882140/31007827-18cf1630-a502-11e7-99b6-0db812eb26b2.png)
![screenshot_2017-09-28-21-25-13](https://user-images.githubusercontent.com/10882140/31007825-18cd54ee-a502-11e7-95a6-947271ae517a.png)
![screenshot_2017-09-28-21-26-49](https://user-images.githubusercontent.com/10882140/31007828-18ccfa76-a502-11e7-9a7a-0cfdae25aa6d.png)
![screenshot_2017-09-28-21-27-05](https://user-images.githubusercontent.com/10882140/31007826-18cd76ea-a502-11e7-820e-50158fdb5803.png)
![screenshot_2017-09-28-21-57-03](https://user-images.githubusercontent.com/10882140/31007829-18e4979e-a502-11e7-9d9b-dc1c5b8346c4.png)

**Comment by nosijf982** [comment]
Muchas gracias por avisar, ultimamente no tenemos muchas personas disponibles para la traducción así que está un poco incompleta :-/. Cuando tenga un rato arreglo eso ;)

**Comment by nosijf982** [comment]
Algunas cosas ya están arregladas, otras no soy capaz de encontrarlas :( . Si hay novedades te comento

**Comment by migui88** [comment]
Bueno, tampoco hace falta que se arreglen de un día para otro... Gracias por colaborar!

**Comment by migui88** [comment]
He encontrado nuevos fallos en la versión. Los widgets de música no están traducidos
![screenshot_2017-09-30-14-51-50](https://user-images.githubusercontent.com/10882140/31047531-dd6b9198-a60c-11e7-89e5-bd958083cd6a.png)

Por otro lado, en la aplicación de navegador que viene, en opciones aparecen algunas cosas sin traducir tampoco. La ventana que aparece sale cuando pinchas en Restore default location
![screenshot_2017-09-30-14-54-50](https://user-images.githubusercontent.com/10882140/31047533-ef40f5f2-a60c-11e7-8c9e-a6e0cb5b082b.png)

Saludos!!!

**Comment by nosijf982** [comment]
Muchísimas gracias por avisarnos ;). Espero que la próxima versión ya no tenga ningún de esos problemas.
Saludos

**Comment by Infante007** [comment]
Buenas  @migui88 pensamos que esta todo corregido, en la siguiente actualizacion nos avisas si ves algo en ingles y lo cambiaremos.
