### ISSUE TITLE
WIFI en HMNote4X no funciona

### ISSUE THREAD

**Issue by Drose1399** [ingbrzy/MA-XML-9.0-SPANISH#112]
En mi movil el wifi no se conecta, pone que no puede encontrar la ip, y por lo tanto no se conecta. No se que hacer he probado a actualizar y a poner actualizaciones anteriores y no me funciona nada, me podeis ayudar, por favor?

**Comment by Infante007** [comment]
Hola @Drose1399 el tema que aqui tratamos es sobre fallos en la traduccion al español.
Ve al foro y pregunta hay si alguien tiene tu problema, pero pon los datos de cual es tu movil ,version de rom etc
