### ISSUE TITLE
A lot untranslated strings in the ROM

### ISSUE THREAD

**Issue by nosijf982** [ingbrzy/MA-XML-9.0-SPANISH#17]
Hello @ingbrzy, a lot of strings aren't translated in rom but in the repo they are.

Here some examples

![85e263d6-6bbf-41d5-9024-720ef4b2e32e](https://user-images.githubusercontent.com/16381926/32677669-a3cf5d70-c65f-11e7-8350-ef5f41ecb8fb.jpg)
![a85245b2-1fb9-4692-b172-42759cca3d11](https://user-images.githubusercontent.com/16381926/32677670-a3ee1cce-c65f-11e7-9db8-05b76a4553e4.jpg)
![sin titulo](https://user-images.githubusercontent.com/16381926/32677671-a407f338-c65f-11e7-899c-e2d0255a6d36.png)
![1e12b623-faca-4198-be68-64d5eb4490bc](https://user-images.githubusercontent.com/16381926/32677673-a422a106-c65f-11e7-90fa-c37ab7f10de0.jpg)

Regards

**Comment by nosijf982** [comment]
At least i tried

**Comment by Infante007** [comment]
El siempre ayudando.....

**Comment by ingbrzy** [comment]
- you have not translated MiuiVideoLeo.apk (copy of MIUI8 MiuiVideo.apk)
- device info is not translatable
- data info has new strings and you are missing them
- wipe data for CleanMaster

**Comment by nosijf982** [comment]
if you would make only a one "folder" with all apps and strings and not 1 folder for every device...
