### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by Infante007** [ingbrzy/MA-XML-9.0-SPANISH#2]
Hello @ingbrzy 
Give me the permits to work in miui9
regards

**Comment by ingbrzy** [comment]
you are already invited since beginning.. 

https://github.com/ingbrzy/MA-XML-9.0-SPANISH/invitations

**Comment by ingbrzy** [comment]
@Infante007 
always check log after your commits 
https://translators.xiaomi.eu/XML_MIUI9-Spanish-es.html

**Comment by nosijf982** [comment]
@ingbrzy  Please, give permissions to @CristhianEcheverry

**Comment by ingbrzy** [comment]
done

**Comment by nosijf982** [comment]
Thnx
