### ISSUE TITLE
Accesos directos en pantalla de bloqueo (7.11.23)

### ISSUE THREAD

**Issue by isanchezgl** [ingbrzy/MA-XML-9.0-SPANISH#39]
En esta nueva versión de xiaomi EU la 7.11.23 aparece en la pantalla de bloqueo si deslizamos hacia la izquierda una serie de accesos directos los cuales estan mal traducidos.
![photo_2017-11-26_06-38-17](https://user-images.githubusercontent.com/33995653/33237445-6b813efe-d274-11e7-8bc1-a851d39c7904.jpg)

Debería aparecer lo siguiente; 

Contactos
Calendario
Calculadora
Notas

Linterna

**Comment by CristhianEcheverry** [comment]
¡Hola @isanchezgl ! Ya fue corregido, para la próxima actualización estará listo ;)

**Comment by Infante007** [comment]
Listo, un saludo
