### ISSUE TITLE
failure in Spanish language

### ISSUE THREAD

**Issue by Infante007** [ingbrzy/MA-XML-9.0-SPANISH#55]
in settings, installed applications fail

**Comment by Infante007** [comment]
@ingbrzy

**Comment by ingbrzy** [comment]
your arrays are not updated 
https://github.com/ingbrzy/Xiaomi.eu-MIUIv9-XML-Compare/commit/b0bb639c42155f2bffb6d2c2c5c0e3dd33c6e6dd#diff-79aa8b604fb21dffdfa6f565a7030856R58

https://github.com/ingbrzy/Xiaomi.eu-MIUIv9-XML-Compare/commit/b0bb639c42155f2bffb6d2c2c5c0e3dd33c6e6dd#diff-79aa8b604fb21dffdfa6f565a7030856R66
