### ISSUE TITLE
Traducción Mi CLOUD en inglés

### ISSUE THREAD

**Issue by ea2ip** [ingbrzy/MA-XML-9.0-SPANISH#56]
All important things in one place

**Comment by ea2ip** [comment]
Aparece en inglés.

**Comment by Infante007** [comment]
gracias @ea2ip por avisar, ya esta solucionado, cualquier cosa avisanos.
https://github.com/ingbrzy/MA-XML-9.0-SPANISH/commit/a9aefb50ab0b54dc19f97f623d1442d50c457372
