### ISSUE TITLE
Error traducción

### ISSUE THREAD

**Issue by migui88** [ingbrzy/MA-XML-9.0-SPANISH#58]
Hola, 
En la última versión de MIUI me he fijado en que si entras en la opción de ajustes->bateria y rendimiento. Una vez dentro el nombre pasa a ser "Administrador de uso de bateria...." Esto solo pasa en esta opción, en el resto se respeta el nombre y en la versión estable igual, se mantiene el nombre de "bateria y rendimiento". 
Por otro lado pone "POWER" en vez de poner energía. 
![screenshot_2017-12-12-20-16-02](https://user-images.githubusercontent.com/10882140/33962079-9a9ed3d8-e050-11e7-9ee5-f1af071cdc42.png)

También me he fijado en que si pinchas dentro de Escenarios, la opción de modo de ahorro nocturno está en ingles. 
![screenshot_2017-12-12-20-15-52](https://user-images.githubusercontent.com/10882140/33962207-0807fb52-e051-11e7-8fbf-294b4d6c96f0.png)
Saludos

**Comment by Infante007** [comment]
Muchas gracias @migui88 por el aviso, lo primero arreglado:
https://github.com/ingbrzy/MA-XML-9.0-SPANISH/commit/9b5e8fc94e0cceabd0a5328b5a02e835a19121ce
Lo segundo:
https://github.com/ingbrzy/MA-XML-9.0-SPANISH/commit/edb13dc19d13ee7aaba60c36bc15cf99c9d85b7f

Cualquier cosa nos avisas.
un abrazo
