### ISSUE TITLE
Interesado en participar en la traducción al español

### ISSUE THREAD

**Issue by le-zurdo** [ingbrzy/MA-XML-9.0-SPANISH#7]
Interesado y entusiasta de ayudar para ser exactos, ¿que se necesita para colaborar @Infante007 ?

**Comment by nosijf982** [comment]
Ganas de trabajar ;), toda la ayuda es bienvenida. Solo necesitamos un nick de telegram para comunicarnos y te contamos como va todo.

Saludos :D

**Comment by le-zurdo** [comment]
Cierto, olvidaba ese dato XD
Mi nick de Telegram es le_zurdo
https://telegram.me/le_zurdo

**Comment by nosijf982** [comment]
Listo, nos vemos en Telegram
