### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by Infante007** [ingbrzy/MA-XML-9.0-SPANISH#72]
hello @ingbrzy 
Does @CristhianEcheverry  have the permissions to make changes in the repertoire?
thx

**Comment by ingbrzy** [comment]
Invitation sent few months ago.. 
https://github.com/ingbrzy/MA-XML-9.0-SPANISH/invitations

**Comment by Infante007** [comment]
I do not, they are for @CristhianEcheverry

**Comment by CristhianEcheverry** [comment]
Ready
