### ISSUE TITLE
Error traducción aplicación correo

### ISSUE THREAD

**Issue by migui88** [ingbrzy/MA-XML-9.0-SPANISH#77]
Hola,
En la última weekly, 7.12.21 me he fijado que en la aplicación de correo cuando escribes un email aparece el destinatario con la palabra "To" en vez de "Para". 
Un saludo!
![screenshot_2017-12-28-11-27-24](https://user-images.githubusercontent.com/10882140/34408228-de18bcdc-ebc2-11e7-95bb-1c4a2084c3a7.png)

**Comment by Infante007** [comment]
https://github.com/ingbrzy/MA-XML-9.0-SPANISH/commit/fc7cf77da22b9884502c24f5fef2a9be1697dea0
Listo

**Comment by Infante007** [comment]
hola @migui88 hay algun problema con el bot y borra la traducción que hacemos de TO
Haber si el que tiene la opción lo arregla

**Comment by migui88** [comment]
Hola, en la versión 8.3.1 sigue pasando lo mismo. 
Saludos
