### ISSUE TITLE
Configuracion restablecer telefono

### ISSUE THREAD

**Issue by ibus00** [ingbrzy/MA-XML-9.0-SPANISH#80]
tengo la estable redmi note 4 mtk 9.2, en configuracion - ajstes adicionales--- copia de seg--- restablecer datos , cuando sale el letrero de advertencia sale <b & # 8820 ; Restablecer datos .... 
tambien en la siguiente pantalla sale la b entre corchetes

**Comment by nosijf982** [comment]
Hola @ibus00, le echo un vistazo gracias por avisar

**Comment by nosijf982** [comment]
Arreglado 16ad2c4 , si hay algun problema más avisanos
