### ISSUE TITLE
Me gustaría ayudar a traducir o corregir errores

### ISSUE THREAD

**Issue by MrAnnix** [ingbrzy/MA-XML-9.0-SPANISH#82]

**Comment by nosijf982** [comment]
Hola @MrAnnix, danos un nick de telegram y te comentamos como va todo!

Saludos ;)

**Comment by MrAnnix** [comment]
Hola, @MrAnnix también.

El 21 ene. 2018 1:14 p. m., "Nosi" <notifications@github.com> escribió:

Hola @MrAnnix <https://github.com/mrannix>, danos un nick de telegram y te
comentamos como va todo!

Saludos ;)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ingbrzy/MA-XML-9.0-SPANISH/issues/82#issuecomment-359243922>,
or mute the thread

**Comment by nosijf982** [comment]
Listo!
