### ISSUE TITLE
Wrong translation. xiaomi.eu MIUI 9.3 8.1.25 V2, Mi Mix 2

### ISSUE THREAD

**Issue by sheuronazxe** [ingbrzy/MA-XML-9.0-SPANISH#88]
english = "Tap to share password"
spanish = "Conectado. Se requiere verificación"

![a](https://user-images.githubusercontent.com/9971945/35471206-c87a68ca-0356-11e8-933e-25d9e846f4c1.png)

**Comment by Infante007** [comment]
Hola @sheuronazxe .
Ya esta corregido saldra para la siguiente semana.
https://github.com/ingbrzy/MA-XML-9.0-SPANISH/commit/0a1d2dfa0d0e5b2a42b2d45e948a144238c8e293
gracias
