### ISSUE TITLE
traducción

### ISSUE THREAD

**Issue by DALEXS88** [ingbrzy/MA-XML-9.0-SPANISH#9]
Buen Día
Deseo participar en la traducción
cuales son los requisitos

Gracias por su amable atención

**Comment by nosijf982** [comment]
Los requisitos son ganas de trabajar :D, pasanos tu nick de telegram y te contamos como va el tinglao.

Saludos ;)

**Comment by DALEXS88** [comment]
https://t.me//DALEXS
