### ISSUE TITLE
Traducciones al español (pregunta)

### ISSUE THREAD

**Issue by vacilagodzila** [ingbrzy/MA-XML-9.0-SPANISH#93]
Saludos, estoy interesado en contribuir en su repo ¿Cómo podría proceder? Gracias!

**Comment by nosijf982** [comment]
Ola @vacilagodzila , mandanos tu nick de telegram y te comentamos como va todo

**Comment by vacilagodzila** [comment]
Mi alias es @scci96

**Comment by nosijf982** [comment]
Perfecto!
